### These requiests have predefined port values to simplify demonstration

### Request to companion-source-api service

http://localhost:8800/weatherforecast

### Request to companion-containerized-api service

http://localhost:8801/weatherforecast